# Check if packages are installed and if they are not installed, install them
packages <- c("devtools", "tidyverse", "data.table", "naniar", "ape")
cran_packages <- setdiff(packages, rownames(installed.packages()))
if( length(cran_packages) ) {
  if( length(grep("devtools", cran_packages))) {
    install.packages("devtools")
  }
  require(devtools)
  if( length(grep("tidyverse", cran_packages))) {
    install_version("tidyverse", version = "1.3.1", repos = "http://cran.us.r-project.org")
  }
  if( length(grep("data.table", cran_packages))) {
    install_version("data.table", version = "1.14.0", repos = "http://cran.us.r-project.org")
  }
  if( length(grep("naniar", cran_packages))) {
    install_version("naniar", version = "0.6.1", repos = "http://cran.us.r-project.org")
  }
  if( length(grep("ape", cran_packages))) {
    install_version("ape", version = "5.5", repos = "http://cran.us.r-project.org")
  }
}
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
bioc_packages <- "ggtree"
bioc_missing <- setdiff("ggtree", rownames(installed.packages())) 
if( length(bioc_missing) ) {
  BiocManager::install("ggtree", version = "2.99.0")
}

# Load packages
library(tidyverse)
library(data.table)
library(naniar)
library(ape)
library(ggtree)

rm(list = ls())

# Functions

# Create a new directory or delete and replace an existing directory
# From https://stackoverflow.com/questions/38375305/how-to-overwrite-a-folder-on-the-computer-using-functions-in-r
make.dir <- function(fp) {
  if(!file.exists(fp)) {  # If the folder does not exist, create a new one
    make.dir(dirname(fp))
    dir.create(fp)
  } else {   # If it existed, delete and replace with a new one  
    unlink(fp, recursive = FALSE)
    dir.create(fp)
  }
} 

# Format data for creation of nexus file
nexus_formatting <- function(data){
  # Convert data to data frame
  data <- as.data.frame(data)
  # Convert NA to ?
  data[is.na(data)] <- "?"
  # Add row names
  data <- as.data.frame(data)
  row.names(data) <- data$`Entry ID`
  data <- data %>% select(-`Entry ID`, -`Entry name`)
  # Convert to matrix
  data <- as.matrix(data)
}

# Write morphological nexus data, based on write.nexus.data from ape
# input is a matrix with row names as taxa labels, a single column data frame with character labels and output files
write_morph_nexus <- function (x, char_labels, file, gap = NULL, missing = NULL) {
  indent <- "        "
  maxtax <- 5
  charsperline <- ncol(x)
  defgap <- "-"
  defmissing <- "?"
  if (is.matrix(x)) {
    xbak <- x
    x <- vector("list", nrow(xbak))
    for (i in seq_along(x)) x[[i]] <- xbak[i, ]
    names(x) <- rownames(xbak)
    rm(xbak)
  }
  ntax <- length(x)
  nchars <- length(x[[1]])
  zz <- file(file, "w")
  if (is.null(names(x))) 
    names(x) <- as.character(1:ntax)
  fcat <- function(..., file = zz) cat(..., file = file, sep = "", 
                                       append = TRUE)
  find.max.length <- function(x) max(nchar(x))
  print.matrix <- function(x, dindent = "    ", collapse = "") {
    Names <- names(x)
    printlength <- find.max.length(Names) + 2
    ntimes <- ceiling(nchars/charsperline)
    start <- 1
    end <- charsperline
    for (j in seq_len(ntimes)) {
      for (i in seq_along(x)) {
        sequence <- paste(x[[i]][start:end], collapse = collapse)
        taxon <- Names[i]
        thestring <- sprintf("%-*s%s%s", printlength, 
                             taxon, dindent, sequence)
        fcat(thestring, "\n")
      }
      if (j < ntimes) 
        fcat("\n")
      start <- start + charsperline
      end <- end + charsperline
      if (end > nchars) 
        end <- nchars
    }
  }
  fcat("#NEXUS\n[Generated by write_morph_nexus.R, ", date(), 
       "]\n\n")
  NCHAR <- paste("NCHAR=", nchars, sep = "")
  NTAX <- paste0("NTAX=", ntax)
  if (is.null(missing)) 
    missing <- defmissing
  MISSING <- paste0("MISSING=", missing)
  if (is.null(gap)) 
    gap <- defgap
  GAP <- paste0("GAP=", gap)
  fcat("BEGIN TAXA;\n")
  fcat(indent, "TITLE  combined;\n")
  fcat(indent, "DIMENSIONS ", NTAX, ";\n") 
  fcat(indent, "TAXLABELS\n")
  fcat(indent, "  ")
  for (i in seq_len(ntax)) {
    fcat(names(x)[i], "\n")
    fcat(indent, "  ")
  }
  fcat(";\n")
  fcat("END;\n\n")
  fcat("BEGIN CHARACTERS;\n")
  fcat(indent, "TITLE  Character Descriptions;\n")
  fcat(indent, "LINK TAXA = combined;\n")
  fcat(indent,"DIMENSIONS ", NCHAR, ";\n")
  fcat(indent,'FORMAT DATATYPE=Standard SYMBOLS= "0 1 2 3 4 5 6 7 8 9" ', MISSING, " ", GAP, ";\n")
  fcat("\nMATRIX\n")
  print.matrix(x)
  fcat(";\nEND;\n")
  close(zz)
}

# Plot tree with edge lengths
plot_tree_edge <- function(tree){
  edges <- data.frame(tree$edge, edge_length=round(tree$edge.length,2)) %>% 
    rename("parent" = "X1", "node" = "X2")
  tree <- ggtree(tree) %<+% edges + geom_text(aes(x = branch, label = edge_length), size = 2, hjust = -.2, vjust=-.2) 
}

